### ISSUE TITLE
About the reproduce results?

### ISSUE THREAD

**Issue by JCZ404** [LYMDLUT/DAB_DETR_mmdetection#1]
Hi~, thank you for your great work, but I wonder if you reproduce the results reported in the paper or the official repo, i.e. 42.2 mAP ?

**Comment by LYMDLUT** [comment]
![image](https://user-images.githubusercontent.com/70597027/179768200-f2be49bb-4b03-4ff2-bc1f-267248641256.png)
preview

**Comment by JCZ404** [comment]
OK, thanks for your answer!

**Comment by LYMDLUT** [comment]
Although  there is still a lot of work to do，i still release the model and logs.
